export type Lang = "en" | "mm";

export const copy = {
  en: {
    tagline: "Yangon Cafe & Tea Guide",
    saved: "Saved",
    heroTitle: "Find a coffee shop in Yangon",
    heroBody: "Search by name, pick a township, or find cafes near you.",
    howItWorks: "How it works",
    step1Title: "Search or filter",
    step1Body: "Type a cafe name, pick a township, or tap what you need — Wi-Fi, still open, or a quiet place to work.",
    step2Title: "Browse the list",
    step2Body: "See ratings, hours, and what’s available at each spot so you can choose with confidence.",
    step3Title: "Go visit",
    step3Body: "Open a cafe for the address, opening hours, and directions on the map.",
    placesCount: (n: number) => `${n} cafes in the guide`,
    resultsCount: (n: number) => `${n} cafes in this list`,
    startTitle: "No township selected yet",
    startBody: "Tap a township above to see cafes in that neighborhood. You can also search by name or use Cafes Near Me.",
    choosePrompt: "Start here — choose a township",
    startOver: "Start over",
    popularTownships: "Popular townships",
    searchLabel: "Search cafes in Yangon",
    searchPlaceholder: "Search by cafe name, street, or coffee style...",
    clearSearch: "Clear search query",
    nearMe: "Cafes Near Me",
    locating: "Finding nearby cafes…",
    locationActive: "Location active",
    moreTownships: "More",
    kmAway: "",
    photoUnavailable: "No photo yet",
    filterBy: "Filter by:",
    stillOpen: "Still Open",
    wifi: "Wi-Fi",
    workFriendly: "Work Friendly",
    petFriendly: "Pet Friendly",
    ratingOver4: "Rating over 4",
    allTownships: "All Townships",
    chooseTownship: "Choose township",
    townshipFilter: "Filter by township",
    resetFilters: "Reset filters",
    loadingMore: "Loading more spots...",
    seenAll: (n: number) => `You have seen all ${n} cafes in this list.`,
    emptyTitle: "No cafes found",
    emptyBody:
      "We couldn't find any cafes matching your search or filters. Try another township, or start over.",
    openNow: "Open now",
    closed: "Closed",
    viewDetails: "View Details",
    cafeNotFound: "Cafe Not Found",
    cafeNotFoundBody: "The cafe you are looking for could not be found or has been moved.",
    returnGuide: "Return to Cafe Guide",
    backToAll: "Back to all cafes",
    saveFavorite: "Save to favorites",
    savedFavorite: "Saved to favorites",
    openRightNow: "Open right now",
    currentlyClosed: "Currently closed",
    townshipSuffix: "Township",
    outOfFive: "out of 5.0",
    aboutCafe: "About This Cafe",
    whatYoullFind: "What you'll find here",
    ratingTitle: "Rating",
    ratingFrom: "From",
    visitingDetails: "Visiting Details",
    locationAddress: "Location & Address",
    openingHours: "Opening Hours",
    everyday: "Everyday:",
    visitWebsite: "Visit Official Website",
    getDirections: "Get Directions on Google Maps",
    footerCurated: "A simple cafe guide for Yangon",
    footerData: "OpenStreetMap & Google Maps data",
    footerCulture: "Yangon coffee culture",
    locationDenied:
      "Location access was denied. You can still search by township or cafe name.",
    locationUnsupported: "This browser does not support location. You can still search by township.",
    ratingFallback: "Google Maps & OpenStreetMap",
  },
  mm: {
    tagline: "ရန်ကုန် ကော်ဖီနှင့် လက်ဖက်ရည်လမ်းညွှန်",
    saved: "သိမ်းထားသည်",
    heroTitle: "ရန်ကုန်မှာ ကော်ဖီဆိုင် ရှာပါ",
    heroBody: "အမည်ဖြင့် ရှာပါ၊ မြို့နယ်ရွေးပါ၊ သို့မဟုတ် အနီးရှိဆိုင်များကို ကြည့်ပါ။",
    howItWorks: "ဘယ်လိုသုံးရမလဲ",
    step1Title: "ရှာဖွေ သို့မဟုတ် စစ်ထုတ်ပါ",
    step1Body: "ဆိုင်အမည် ရိုက်ပါ၊ မြို့နယ်ရွေးပါ၊ သို့မဟုတ် Wi-Fi၊ ဖွင့်နေဆဲ၊ အလုပ်လုပ်ရန် သင့်တော်သောနေရာ စသည်တို့ကို နှိပ်ပါ။",
    step2Title: "စာရင်းကို ကြည့်ပါ",
    step2Body: "အဆင့်သတ်မှတ်ချက်၊ ဖွင့်ချိန်နှင့် ဆိုင်တွင်ရှိသော အရာများကို ကြည့်ပြီး စိတ်ချလက်ချ ရွေးချယ်နိုင်ပါသည်။",
    step3Title: "သွားရောက်ပါ",
    step3Body: "လိပ်စာ၊ ဖွင့်ချိန်နှင့် မြေပုံလမ်းညွှန်များအတွက် ဆိုင်တစ်ဆိုင်ကို ဖွင့်ပါ။",
    placesCount: (n: number) => `လမ်းညွှန်တွင် ဆိုင် ${n} ဆိုင်`,
    resultsCount: (n: number) => `ဤစာရင်းတွင် ဆိုင် ${n} ဆိုင်`,
    startTitle: "မြို့နယ် မရွေးရသေးပါ",
    startBody: "အပေါ်မှ မြို့နယ်တစ်ခုကို နှိပ်ပါ။ ဆိုင်အမည်ဖြင့်လည်း ရှာနိုင်သည်၊ သို့မဟုတ် အနီးရှိဆိုင်များကို သုံးနိုင်သည်။",
    choosePrompt: "ဤနေရာမှ စတင်ပါ — မြို့နယ်ရွေးပါ",
    startOver: "ပြန်လည်စတင်ရန်",
    popularTownships: "လူကြိုက်များသော မြို့နယ်များ",
    searchLabel: "ရန်ကုန်ရှိ ကော်ဖီဆိုင်များ ရှာဖွေရန်",
    searchPlaceholder: "ဆိုင်အမည်၊ လမ်း သို့မဟုတ် ကော်ဖီအမျိုးအစားဖြင့် ရှာပါ...",
    clearSearch: "ရှာဖွေမှုကို ရှင်းရန်",
    nearMe: "အနီးရှိဆိုင်များ",
    locating: "အနီးရှိဆိုင်များ ရှာနေသည်…",
    locationActive: "တည်နေရာ အသုံးပြုနေသည်",
    moreTownships: "နောက်ထပ်",
    kmAway: "အကွာ",
    photoUnavailable: "ဓာတ်ပုံ မရှိသေးပါ",
    filterBy: "စစ်ထုတ်ရန်:",
    stillOpen: "ဖွင့်နေဆဲ",
    wifi: "Wi-Fi",
    workFriendly: "အလုပ်လုပ်ရန် သင့်တော်",
    petFriendly: "အိမ်မွေးတိရစ္ဆာန် ခွင့်ပြု",
    ratingOver4: "အဆင့် ၄ နှင့်အထက်",
    allTownships: "မြို့နယ်အားလုံး",
    chooseTownship: "မြို့နယ်ရွေးပါ",
    townshipFilter: "မြို့နယ်အလိုက် စစ်ထုတ်ရန်",
    resetFilters: "စစ်ထုတ်မှုများ ပြန်လည်သတ်မှတ်",
    loadingMore: "နောက်ထပ်နေရာများ တင်နေသည်...",
    seenAll: (n: number) => `ဤစာရင်းရှိ ဆိုင် ${n} ဆိုင်လုံးကို ကြည့်ပြီးပါပြီ။`,
    emptyTitle: "ဆိုင်များ မတွေ့ပါ",
    emptyBody:
      "ရှာဖွေမှု သို့မဟုတ် စစ်ထုတ်မှုနှင့် ကိုက်ညီသော ဆိုင်မရှိပါ။ အခြားမြို့နယ်ကို ရွေးပါ သို့မဟုတ် ပြန်လည်စတင်ပါ။",
    openNow: "ဖွင့်နေသည်",
    closed: "ပိတ်ထားသည်",
    viewDetails: "အသေးစိတ်ကြည့်ရန်",
    cafeNotFound: "ဆိုင်ကို မတွေ့ပါ",
    cafeNotFoundBody: "သင်ရှာနေသော ဆိုင်ကို ရှာမတွေ့ပါ သို့မဟုတ် ရွှေ့ထားခြင်းဖြစ်နိုင်သည်။",
    returnGuide: "လမ်းညွှန်သို့ ပြန်သွားရန်",
    backToAll: "ဆိုင်အားလုံးသို့ ပြန်ရန်",
    saveFavorite: "သိမ်းရန်",
    savedFavorite: "သိမ်းပြီးပါပြီ",
    openRightNow: "ယခု ဖွင့်နေသည်",
    currentlyClosed: "ယခု ပိတ်ထားသည်",
    townshipSuffix: "မြို့နယ်",
    outOfFive: "၅.၀ အနက်",
    aboutCafe: "ဤဆိုင်အကြောင်း",
    whatYoullFind: "ဤနေရာတွင် တွေ့နိုင်သည်များ",
    ratingTitle: "အဆင့်သတ်မှတ်ချက်",
    ratingFrom: "ရင်းမြစ်",
    visitingDetails: "သွားရောက်ရန် အချက်အလက်",
    locationAddress: "တည်နေရာနှင့် လိပ်စာ",
    openingHours: "ဖွင့်ချိန်",
    everyday: "နေ့စဉ်:",
    visitWebsite: "တရားဝင်ဝက်ဘ်ဆိုက်သို့ သွားရန်",
    getDirections: "Google Maps တွင် လမ်းညွှန်ကြည့်ရန်",
    footerCurated: "ရန်ကုန်အတွက် ရိုးရှင်းသော ကော်ဖီဆိုင်လမ်းညွှန်",
    footerData: "OpenStreetMap နှင့် Google Maps ဒေတာ",
    footerCulture: "ရန်ကုန် ကော်ဖီယဉ်ကျေးမှု",
    locationDenied:
      "တည်နေရာခွင့်ပြုချက်ကို ပယ်ချထားသည်။ မြို့နယ် သို့မဟုတ် ဆိုင်အမည်ဖြင့် ဆက်လက်ရှာနိုင်ပါသည်။",
    locationUnsupported: "ဤဘရောက်ဇာသည် တည်နေရာကို မပံ့ပိုးပါ။ မြို့နယ်ဖြင့် ဆက်လက်ရှာနိုင်ပါသည်။",
    ratingFallback: "Google Maps နှင့် OpenStreetMap",
  },
} as const;

export function getCopy(lang: Lang) {
  return copy[lang];
}

export function ratingSourceLabel(sources: string[] | undefined, lang: Lang): string {
  const list = sources ?? [];
  const hasGoogle = list.some((s) => /google/i.test(s));
  const hasOsm = list.some((s) => /openstreetmap/i.test(s));

  if (hasGoogle && hasOsm) {
    return lang === "mm" ? "Google Maps နှင့် OpenStreetMap" : "Google Maps & OpenStreetMap";
  }
  if (hasGoogle) return "Google Maps";
  if (hasOsm) return "OpenStreetMap";
  return copy[lang].ratingFallback;
}
